# Generated by Django 5.1.5 on 2025-06-04 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_prevention_virus_alter_scenario_prevention'),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('outfile', models.CharField(max_length=250, null=True)),
                ('export_type', models.CharField(choices=[('ANIMATION', 'Animation'), ('SNAPSHOT', 'Snapshot'), ('EXCESS_RISK', 'Excess Risk'), ('EPIDEMIOLOGICAL_STATUS', 'Epidemiological Status'), ('VIRAL_CONCENTRATION', 'Viral Concentration')], max_length=32)),
                ('params', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.run')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
