# Generated by Django 5.1.5 on 2026-01-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_export'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='outfile',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='run',
            name='config',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='run',
            name='logfile',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='run',
            name='save_dir',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='material',
            field=models.CharField(default='', max_length=250),
        ),
    ]
