version: "3.9"

services:
  api:
    container_name: abs-api
    build: ./backend
    command: bash -c "
        while !</dev/tcp/db/5432; do sleep 1; done;
        python manage.py migrate && python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  db-admin:
    container_name: abs-db-admin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: password
      GUNICORN_ACCESS_LOGFILE: '/dev/null'
    volumes:
      - ./backend/data/pgadmin:/var/lib/pgadmin
    logging:
      driver: none
    depends_on:
      - db

  db:
    container_name: abs-db
    image: postgres
    command: postgres -c stats_temp_directory=/tmp
    volumes:
      - ./backend/data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
