x-common-variables: &common-variables
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

services:
  api:
    container_name: abs-api
    build: ./backend
    command: bash -c "
        while !</dev/tcp/db/5432; do sleep 1; done;
        python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    environment:
      <<: *common-variables
      POSTGRES_NAME: postgres
    depends_on:
      - db

  db-admin:
    container_name: abs-db-admin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: password
      GUNICORN_ACCESS_LOGFILE: '/dev/null'
    volumes:
      - ./backend/data/pgadmin:/var/lib/pgadmin
    logging:
      driver: none
    depends_on:
      - db

  db:
    container_name: abs-db
    image: postgres:14
    command: postgres -c stats_temp_directory=/tmp
    volumes:
      - ./backend/data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      <<: *common-variables
      POSTGRES_DB: postgres

  web:
    container_name: abs-web
    build: ./frontend
    volumes:
      - './frontend:/app'
      - './backend/data/exports:/data/exports'
      - './backend/data/logs:/data/logs'
      - './backend/data/mapfiles:/data/mapfiles'
      - './backend/data/outputs:/data/outputs'
      - './backend/data/run_configs:/data/run_configs'
    entrypoint: ["streamlit", "run", "app.py"]
    ports:
      - 8501:8501
    depends_on:
      - db
      - api
  
  frontend-new:
    build: ./frontend-new
    ports:
      - "5173:5173"
    volumes:
      - ./frontend-new:/app
      - /app/node_modules  
    working_dir: /app
    command: pnpm dev --host
